Added Tests

diff --git a/.github/workflows/main_passwordgenerator.yml b/.github/workflows/main_passwordgenerator.yml
--- a/.github/workflows/main_passwordgenerator.yml
+++ b/.github/workflows/main_passwordgenerator.yml
@@ -11,7 +11,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
+  build-and-test:
     runs-on: ubuntu-latest
     permissions:
       contents: read #This is required for actions/checkout
@@ -40,16 +40,23 @@ jobs:
           path: |
             .
             !antenv/
+      
+      - name: Test
+        run: |
+          echo "Checking for requirements.txt..."
+          test -f requirements.txt  (echo "Error: requirements.txt is missing!" && exit 1)
+          echo "Checking for app.py (or your main application file)..."
+          test -f app.py || (echo "Error: app.py is missing!" && exit 1)
+          echo "All required files found. Proceeding."
 
       # 🚫 Opting Out of Oryx Build
       # If you prefer to disable the Oryx build process during deployment, follow these steps:
       # 1. Remove the SCM_DO_BUILD_DURING_DEPLOYMENT app setting from your Azure App Service Environment variables.
       # 2. Refer to sample workflows for alternative deployment strategies: https://github.com/Azure/actions-workflow-samples/tree/master/AppService
-      
 
   deploy:
     runs-on: ubuntu-latest
-    needs: build
+    needs: build-and-test
     permissions:
       id-token: write #This is required for requesting the JWT
       contents: read #This is required for actions/checkout
